### ISSUE TITLE
Esky doesn't create exe on Linux

### ISSUE THREAD

**Issue by JPFrancoia** [cloudmatrix/esky#80] opened 2015-05-15 16:53 UTC
Hi,
I'm trying to freeze my program on linux, with the bdist_esky command.

Here is my setup.py:

```
import sys
import os
from esky.bdist_esky import Executable
from cx_Freeze import setup


setup(name = "guifoo",
      version = "0.1",
      description = "My GUI application!",
      options = {"bdist_esky":{"freezer_module": "cx_Freeze"}},
      executables = [Executable("gui.py")])

```

But when I run ```python setup.py bdist_esky```, even if the dist folder is created, the zip file inside does not contain executable file.

Here is what I have, after I extracted the zip:

```
guifoo-0.1.linux-x86_64/
    fcntl.cpython-34m.so 
    libpython3.4m.so.1.0
    guifoo-0.1.linux-x86_64/
        array.cpython-34m.so
        _codecs_jp.cpython-34m.so
        grp.cpython-34m.so
        _md5.cpython-34m.so
        ... Some other *.so files....
        esky-files/
            bootstrap-manifest.txt
            lockfile.txt
        library.zip
````

But nothing simply called "guifoo", which would be a runnable binary.
I have to mention if I do ```python setup.py build```, which is the normal command to build with cx_freeze, I have a build/ folder with a perfectly runnable 'guifoo' file inside.

Could you help me to build properly the binary file with esky ?

**Comment by rfk** [comment] 2015-06-13 10:19
Hi @rififi, sorry for the delay in replying here - unfortunately I don't get much time to work on esky these days.  What version of python are you using, and what version of cxfreeze?

**Comment by timeyyy** [comment] 2015-08-11 10:13
i cannot reproduce this can we close this?

**Comment by timeyyy** [comment] 2015-11-18 11:53
Dead

**Closed by timeyyy** 2015-11-18 11:53 UTC
