### ISSUE TITLE
Python 3.3: unable to locate initialization module

### ISSUE THREAD

**Issue by AustinMatherne** [cloudmatrix/esky#38] opened 2013-01-22 02:08 UTC
The built executable for my application runs successfully; however, the bootstrap executable fails to launch with the following
### "cx_Freeze Fatal Error":

"unable to locate initialization module"

I'm using cx_Freeze for compatibility with Python 3. My setup.py follows:

```
from esky.bdist_esky import Executable
from distutils.core import setup

exe = Executable("thinX.py",
            icon = "logo.ico",
            gui_only = True,
          )

project_files = ["AUTHORS.md", "LICENSE.md", "README.md", "TODO.md",
                 "units.ini"]

setup(
  name = "thinX",
  version = "0.2.0",
  description="GUI with various utilities for manipulating XBRL files.",
  author="Austin M. Matherne",
  author_email="AustinMatherne@Gmail.com",
  scripts = [exe],
  data_files = project_files,
  options = {"bdist_esky":{
               "includes": [],
               "excludes": [],
               "freezer_module": "cxfreeze",}
            },
)
```

**Comment by etcher3rd** [comment] 2015-01-27 18:06
Any update on this one ?

**Comment by Ecno92** [comment] 2015-01-27 22:12
This error should be fixed: https://github.com/cloudmatrix/esky/commit/bb6482608d9cc3b291f8828afd8b830b71c1cd28

Are you still experiencing problems? In that case I assume there may be multiple causes of the problem since I tested the fix quite often.

**Comment by etcher3rd** [comment] 2015-01-27 22:14
Sorry for the lack of information in my previous post, I actually did not expect this necro to work...

I'm having this issue with Py 3.4 and the latest Esky & cx_Freeze, boht installed with pip.

**Comment by Ecno92** [comment] 2015-01-27 22:22
Interesting... I didn't test our application with Python 3.4. So there may be something changed again which causes a similar error. Could you maybe fall back to Python 3.3 to see if that works?

Since it takes me some time to set up the environment to investigate it myself I would advice to see what the CX_freeze contributors changed to make freezing work for Python 3.4 in case it breaks on the newest Python version. This helped me last time to create the fix for Python 3.3 compatibility.

**Comment by davethecipo** [comment] 2015-01-31 16:15
Hello everyone, python newbie here!

I can confirm the same bug by running esky with cx_freeze on linux, with both python 3.4 and 3.3. Esky and cx_Freeze are installed inside a virtualenv via pip.

The fix suggested by @Ecno92 works for python 3.3, but it has a side effect: let me illustrate the problem

setup.py

    from distutils.core import setup
    from esky.bdist_esky import Executable
    import os


    executables = [
        Executable(os.path.join('polibeepsync', 'qtgui.py'))
    ]

    data_files = ['.venv34/lib/python3.4/site-packages/requests/cacert.pem']

    setup(
        name="poliBeePsync",
        version="0.3.1a",
        options = {
            "bdist_esky": {
                "freezer_module": "cx_freeze"}},
        scripts=executables,
        data_files = data_files
    )


As you can see, ``data_files`` contains one item. If I extract the zip file created by esky, I see a copy of that file in the subfolder ``poliBeePsync-0.3.1a0.linux-x86_64``.

    extracted_archive/
    ├── cacert.pem
    ├── fcntl.cpython-33m.so
    ├── libpython3.3m.so.1.0
    ├── poliBeePsync-0.3.1a0.linux-x86_64
    │   ├── cacert.pem
    │   ├── esky-files
    │   │   ├── bootstrap-manifest.txt
    │   │   └── lockfile.txt
    OTHER STUFF...
    │   ├── qtgui # => let's call this file (A)
    └── qtgui # => let's call this file (B)

File (A) works like a charm, while file (B) doesn't because it can't find ``cacert.pem`` (I suppose that it looks in the same folder). If I copy ``cacert.pem`` to the main directory, like this...

    extracted_archive/
    ├── cacert.pem
    ├── fcntl.cpython-33m.so
    ├── libpython3.3m.so.1.0
    ├── poliBeePsync-0.3.1a0.linux-x86_64
    │   ├── cacert.pem
    │   ├── esky-files
    │   │   ├── bootstrap-manifest.txt
    │   │   └── lockfile.txt
    OTHER STUFF...
    │   ├── qtgui # => let's call this file (A)
    ├── cacert.pem # here is the copy
    └── qtgui # => let's call this file (B)

...file (B) works too.

**Comment by Ecno92** [comment] 2015-02-02 07:15
I'm quite sure that your problem is not the result of my changes. Unfortunately I don't know what is going wrong exactly and it has been a long time ago for me since I looked into the code of Esky. However I think it may be related to your CX_freeze version. Which version do you use?
We use a specific version of CX_freeze: https://bitbucket.org/anthony_tuininga/cx_freeze/get/a34b832.zip

Beside that a small remark to finding the location of `cacert.pem`: You can use `requests.certs.where()` instead of `['.venv34/lib/python3.4/site-packages/requests/cacert.pem']`. :-)

**Comment by davethecipo** [comment] 2015-02-02 10:10
Thanks for your help, I'll test with that specific version of cx_freeze.

I was actually aware of ``requests.certs.where()`` but it lead to problems with cx_freeze (again! I'm now wondering if cx_freeze has the culprit).

After looking at the issues, I think that my problem is more related to #67, I'll follow that thread too. Sorry for the noise.

**Comment by scriptdeez** [comment] 2015-03-10 22:05
Hi All,

I had this issue when working to initially freeze my application, without Esky. The solution I found to getting the 'requests' module was to include the cacert.pem file as an included Data File, and add a line to the beginning of the code that I used to freeze in order to add the exe's base directory to the PATH var. Also, included 'requests' as a package in the freezer settings.

Within my setup.py:

Mydata_files = [('', glob(r'C:\Python34\Lib\site-packages\requests\cacert.pem'))]

setup(
	name="IK5k",
	version="1.9.7.2",
	scripts = [exe],
    data_files = Mydata_files,
	dist_dir = "Idle Killer 5000",
    options={
                "bdist_esky":{
						"freezer_module": "cx_Freeze",
						"freezer_options": {
							"targetDir": "Idle Killer 5000",
							"excludes": ['pytz'],
							"packages": ['keyring', 'keyring.backends', 'requests', 'apscheduler'],
							},
                }
        }
)


And within my frozen code, I have:

# Point the program towards the base directory to use the ca cert
cert ='cacert.pem'
# or os.environ['REQUESTS_CA_BUNDLE'] = cert 
os.environ['REQUESTS_CA_BUNDLE'] = os.path.join(os.getcwd(), cert)


After this, my generated exe was able to run successfully.

**Comment by rfk** [comment] 2018-02-25 02:33
Thanks for reaching out.  Unfortunately this project is no longer actively maintained, so I'm going to move it into archive mode:

  https://rfk.id.au/blog/entry/archiving-open-source-projects/

**Closed by rfk** 2018-02-25 02:33 UTC
Labels: document
